# These rules apply to the Nitro Umbrella app and all components.

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'spec/*'
    - 'spec/**/*'
    - 'vendor/**/*'
    - 'db/*'
    - 'db/schema.rb'
    - 'bin/*'
    - 'config/**/*'
    - 'test/*'
    - 'app/helpers/*'
    - 'Gemfile'
    - 'Rakefile'


Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Lint/ScriptPermission:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'Guardfile'
    - 'Capfile'

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - io
    - id
    - to
    - by
    - 'on'
    - in
    - at

Rails:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
